---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPClusterConfig
metadata:
  name: cluster00-cp
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: cluster00-cp
  bgpInstances:
  - name: "asn4200001000"
    localASN: 4200001000
    peers:

    - name: "r09"
      peerASN: 65010
      peerAddress: fc00:0:1000::1
      peerConfigRef:
        name: "fabric-peer"

    vrfs:
    - vrfRef: "blue"
      rd: "1000:1"
      importRTs:
        - "4:4"
      exportRTs:
        - "4:4"
      configRef: blue-config

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPClusterConfig
metadata:
  name: cluster00-wkr00
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: cluster00-wkr00
  bgpInstances:
  - name: "asn4200001001"
    localASN: 4200001001
    peers:
    - name: "r10"
      peerASN: 65010
      peerAddress: fc00:0:1001::1
      peerConfigRef:
        name: "fabric-peer"

    vrfs:
    - vrfRef: "blue"
      rd: "1001:1"
      importRTs:
        - "4:4"
      exportRTs:
        - "4:4"
      configRef: blue-config

    - vrfRef: "green"
      rd: "1001:1"
      importRTs:
        - "5:5"
      exportRTs:
        - "5:5"
      configRef: green-config

