---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPClusterConfig
metadata:
  name: k8s-cp-22
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: k8s-cp-22
  bgpInstances:
  - name: "asn4200001000"
    localASN: 4200001000
    peers:

    - name: "r09"
      peerASN: 65010
      peerAddress: fc00:0:1000::3
      peerConfigRef:
        name: "fabric-peer"

    - name: "r10"
      peerASN: 65010
      peerAddress: fc00:0:2000::3
      peerConfigRef:
        name: "fabric-peer"

    vrfs:
    - vrfRef: "blue"
      rd: "1000:1"
      importRTs:
        - "4:4"
      exportRTs:
        - "4:4"
      configRef: blue-config

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPClusterConfig
metadata:
  name: k8s-wkr00
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: k8s-wkr00
  bgpInstances:
  - name: "asn4200001001"
    localASN: 4200001001
    peers:
    - name: "r10"
      peerASN: 65010
      peerAddress: fc00:0:1001::3
      peerConfigRef:
        name: "fabric-peer"

    - name: "r09"
      peerASN: 65010
      peerAddress: fc00:0:2001::3
      peerConfigRef:
        name: "fabric-peer"

    vrfs:
    - vrfRef: "blue"
      rd: "1001:1"
      importRTs:
        - "4:4"
      exportRTs:
        - "4:4"
      configRef: blue-config

    - vrfRef: "green"
      rd: "1001:1"
      importRTs:
        - "5:5"
      exportRTs:
        - "5:5"
      configRef: green-config

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPClusterConfig
metadata:
  name: k8s-wkr01
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: k8s-wkr01
  bgpInstances:
  - name: "asn4200001002"
    localASN: 4200001002
    peers:
    - name: "r13"
      peerASN: 65013
      peerAddress: fc00:0:1002::3
      peerConfigRef:
        name: "fabric-peer"

    - name: "r14"
      peerASN: 65014
      peerAddress: fc00:0:2002::3
      peerConfigRef:
        name: "fabric-peer"
        
    vrfs:
    - vrfRef: "blue"
      rd: "1002:1"
      importRTs:
        - "4:4"
      exportRTs:
        - "4:4"
      configRef: blue-config
      
    - vrfRef: "green"
      rd: "1002:1"
      importRTs:
        - "5:5"
      exportRTs:
        - "5:5"
      configRef: green-config

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPClusterConfig
metadata:
  name: k8s-wkr02
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: k8s-wkr02
  bgpInstances:
  - name: "asn4200001003"
    localASN: 4200001003
    peers:
    - name: "r13"
      peerASN: 65013
      peerAddress: fc00:0:2003::3
      peerConfigRef:
        name: "fabric-peer"

    - name: "r14"
      peerASN: 65014
      peerAddress: fc00:0:1003::3
      peerConfigRef:
        name: "fabric-peer"
        
    vrfs:
    - vrfRef: "blue"
      rd: "1003:1"
      importRTs:
        - "4:4"
      exportRTs:
        - "4:4"
      configRef: blue-config
      
    - vrfRef: "green"
      rd: "1003:1"
      importRTs:
        - "5:5"
      exportRTs:
        - "5:5"
      configRef: green-config