---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPNodeConfigOverride
metadata:
  name: k8s-cp-22
spec:
  bgpInstances:
    - name: "asn4200001000"
      routerID: "10.10.10.2"
      srv6Responder: true
      peers:
        - name: "r09"
          localAddress: fc00:0:1000::2
        - name: "r10"
          localAddress: fc00:0:2000::2
        # - name: "xrd01"
        #   localAddress: fc00:0:1000::2

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPNodeConfigOverride
metadata:
  name: k8s-wkr00
spec:
  bgpInstances:
    - name: "asn4200001001"
      routerID: "10.10.11.2"
      srv6Responder: true
      peers:
        - name: "r10"
          localAddress: fc00:0:1001::2
        - name: "r09"
          localAddress: fc00:0:2001::2
        # - name: "xrd01"
        #   localAddress: fc00:0:1001::2
---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPNodeConfigOverride
metadata:
  name: k8s-wkr01
spec:
  bgpInstances:
    - name: "asn4200001002"
      routerID: "10.10.12.2"
      srv6Responder: true
      peers:
        - name: "r13"
          localAddress: fc00:0:1002::2
        - name: "r14"
          localAddress: fc00:0:2002::2
        # - name: "xrd05"
        #   localAddress: fc00:0:5::2
---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPNodeConfigOverride
metadata:
  name: k8s-wkr02
spec:
  bgpInstances:
    - name: "asn4200001003"
      routerID: "10.10.13.2"
      srv6Responder: true
      peers:
        - name: "r13"
          localAddress: fc00:0:2003::2  
        - name: "r14"
          localAddress: fc00:0:1003::2
        # - name: "xrd05"
        #   localAddress: fc00:0:5::2
