---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPNodeConfigOverride
metadata:
  name: cluster00-cp
spec:
  bgpInstances:
    - name: "asn4200001000"
      routerID: "10.10.10.2"
      srv6Responder: true
      peers:
        - name: "r09"
          localAddress: fc00:0:1000::2

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPNodeConfigOverride
metadata:
  name: cluster00-wkr00
spec:
  bgpInstances:
    - name: "asn4200001001"
      routerID: "10.10.11.2"
      srv6Responder: true
      peers:
        - name: "r10"
          localAddress: fc00:0:1001::2

