apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.10.10.2:6443
    token: "9yfoao.a7o79szgh57s2zmp"
    caCertHashes:
    - "sha256:093844767d0592e046cc8fae7cc484b2fca82a355226a00966faf944b14984ae"
nodeRegistration:
  kubeletExtraArgs:
  - name: "node-ip"
    value: "10.10.11.2,fc00:0:1001::2"