apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.10.12.2:6443
    token: "g9arwy.8j3lkzg3hksk7gk9"
    caCertHashes:
    - "sha256:fcbb771b1b1e240c22c4c67c20bc015fe0710aaeb197d85d621e7852bd100e7c"
nodeRegistration:
  kubeletExtraArgs:
  - name: "node-ip"
    value: "10.10.13.2,fc00:0:1003::2"